name: Deploy to Public Repo

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Clone target repository
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          git clone --branch gh-pages https://Charmidevdb:${{ secrets.DEPLOY_TOKEN }}@github.com/Charmidevdb/Charmidevdb.c2s-frontend.io.git target-repo

      - name: Copy build files
        run: rsync -av --delete dist/ target-repo/

      - name: Commit and push changes
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          cd target-repo
          git config --global user.name "Charmidevdb"
          git config --global user.email "micheyann57@gmail.com"
          git add .
          git commit -m "Auto-deploy" || echo "No changes to commit"
          git push --force https://Charmidevdb:${{ secrets.DEPLOY_TOKEN }}@github.com/Charmidevdb/Charmidevdb.c2s-frontend.io.git gh-pages
